name: Notion Check and Notify

on:
  schedule:
    - cron: '0 * * * *'  # 毎時実行

jobs:
  check_notion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Notion Check Script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python check_notion.py
